### PR TITLE
Context Menu and Shortcut

### LINKED ISSUE #12: idea: Integrate with right-click menu
Self-explanatory :)

If you right click on a non-link, it'd be for the page (as if you pressed the extension button).

### PR DESCRIPTION
**Pull request by kiichi**
Key_phrase_extraction_using_the_Text_Analytics_REST_API_-_Azure_Cognitive_Services___Microsoft_Docs

### CODE REVIEW

**Comment by kiichi** [comment]
TODO : Manage "Checked" state

**Comment by alejandro5042** [comment]
Awesome.

I'm assuming this works on:

- Right-click on a link
- Right-click on something else, in which case the link is for the tab

**Comment by kiichi** [comment]
ah ok I probably took it wrong, right click on hyper link is not working in this version because I have to access to the contents inside tab. I'll research about it. 
It's in general blank area which brings the same menu so you don't have to look for the icon in the tool bar. let me create another item in the todo list.
https://github.com/kiichi/QuickCopyTitleAndURL/projects/1#card-38391259

**Comment by alejandro5042** [comment]
_Aside:_

A big reason I installed this extension was its reasonable permissions:

image

Extensions that "read and write" on all my web pages... ick :)

**Comment by kiichi** [comment]
@alejandro5042 yeah is that browsing history displayed because of storage? Not sure which one triggers, but I need storage to proceed for settings screen though

Here is corresponding list below and I also submitted justification for each permission
```
"permissions": [
    "tabs",
    "clipboardWrite",
    "notifications",
    "storage"
  ],
```

**Comment by alejandro5042** [comment]
I think it’s because of tabs.

Right now I’m ok with the permissions as listed. There’s another permission that the extension doesn’t get have that’s “read and write your data on all your webpages.” That’s the one I try to avoid.

**Pull request merged**
